language: python
python:
  - 3.4
install:
  - pip install -r dev-requirements.in
  - python setup.py install
script:
  - python setup.py test
#  - flake8 --ignore=E221,E501 challengeauth.py test_challengeauth.py
