version: '2'
services:
  xonotic_stable:
    build:
      context: build
      dockerfile: containers/xonotic_stable.Dockerfile
    command: ./server_linux.sh -game data_csprogs -game data_insta -sessionid insta +serverconfig configs/info-overkill.cfg
    ports:
      - "26011-26014:26011-26014/udp"
  xonotic_git:
    build:
      context: build
      dockerfile: containers/xonotic_git.Dockerfile
    # Run a single server
    #command: ./all run dedicated +serverconfig server.cfg
    command: ./all run dedicated -game modpack -game data_csprogs -game data_insta -sessionid insta +serverconfig configs/info-usainsta.cfg
    # Run many servers (in progress)
    command: xsms servers run
    ports:
      - "26000-26010:26000-26010/udp"
    volumes:
      - ~/.xonotic-smb:/root/.xonotic
      - ~/.xsms.cfg:/root/.xsms.cfg
      - ~/.xsms/servers.yml:/root/.xsms/servers.yml
      - ./xsms:/opt/xsms/xsms
      - ./setup.py:/opt/xsms/setup.py
      - ./README.md:/opt/xsms/README.md
      - ./LICENSE:/opt/xsms/LICENSE